name: 🐛 Bug Report
# title: " "
description: Problems with HUB
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an [Ultralytics HUB](https://ultralytics.com/hub) 🐛 Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/ultralytics/hub/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: HUB Component
      description: |
        Please select the part of the HUB where you found the bug.
      multiple: true
      options:
        - "Signin"
        - "Datasets"
        - "Models"
        - "Projects"
        - "Settings"
        - "API Key"

    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        - Computer: iMac (Retina 5K, 27-inch, Late 2020)
        - OS: MacOS 11.6.1
        - Browser: Chrome Version 95.0.4638.69 (Official Build) (x86_64)

    validations:
      required: false

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
        This is referred to by community members as creating a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: |
        Steps to reproduce the problem, i.e.:
        1. Login to Hub
        2. Click Datasets
        3. ...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/ultralytics/hub/pulls) (PR) to help improve HUB for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the HUB [Contributing Guide](https://github.com/ultralytics/hub/blob/master/CONTRIBUTING.md) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
